# Generated by Django 6.0.4 on 2026-04-22 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('medium_price', models.IntegerField(default=80)),
                ('medium_framed_price', models.IntegerField(default=110)),
                ('large_price', models.IntegerField(default=120)),
                ('large_framed_price', models.IntegerField(default=150)),
            ],
            options={
                'db_table': 'prints',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('size', models.CharField(choices=[('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('frame', models.CharField(choices=[('none', 'None'), ('black', 'Black'), ('wood', 'Wood')], max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('print_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.print')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
    ]
